import { useResource } from '../hooks';
import { formatDate } from '../api';
import ExternalEvaluation from '../components/ExternalEvaluation';
const percent = value => `${(value * 100).toFixed(2)}%`;

function CalibrationCard({ title, model }) {
  if (!model.calibration) return null;
  return <section className="card calibration-card"><div className="eyebrow">PROBABILITY QUALITY</div><h2>{title}</h2><p>{model.calibration.method} · {model.calibration_samples.toLocaleString()} separate calibration samples.</p><div className="model-stats"><div><strong>{model.calibration.before_brier}</strong><span>Brier before</span></div><div><strong>{model.calibration.after_brier}</strong><span>Brier after · lower is better</span></div></div>{model.calibration.after_brier > model.calibration.before_brier && <div className="notice warning">Calibration slightly increased test-set Brier error in this experiment. It should not be described as an improvement in probability quality.</div>}<p className="small">Both values use the same untouched test set. Dataset calibration does not guarantee real-world confidence. The combined threat policy is not calibrated.</p><div className="table-responsive"><table><thead><tr><th>Threshold</th><th>Precision</th><th>Recall</th><th>False positives</th><th>False negatives</th><th>False-positive rate</th></tr></thead><tbody>{model.metrics.thresholds.map(row => <tr key={row.threshold}><td>{row.threshold * 100}/100</td><td>{percent(row.precision)}</td><td>{percent(row.recall)}</td><td>{row.false_positives}</td><td>{row.false_negatives}</td><td>{percent(row.false_positive_rate)}</td></tr>)}</tbody></table></div><details><summary>Reliability bins · predicted vs observed phishing frequency</summary><div className="reliability-bins">{model.metrics.reliability.map((bin, index) => <div key={index}><span>Predicted {percent(bin.predicted)}</span><strong>Observed {percent(bin.observed)}</strong></div>)}</div><p className="small">Nonempty equal-width bins; small bins can be noisy. This is a held-out dataset measurement.</p></details></section>;
}

function BenchmarkCard({ report }) {
  if (!report) return null;
  const metrics = report.metrics;
  return <section className="card benchmark-card"><div className="eyebrow">SEPARATE PUBLISHER TEST / MODERN URLS</div><h2>Generalization beyond the original corpus</h2><p><a href={report.source_url} target="_blank" rel="noreferrer">{report.source} ↗</a></p><div className="model-stats">{[['Accuracy', metrics.accuracy], ['Precision', metrics.precision], ['Recall', metrics.recall], ['F1 score', metrics.f1]].map(([label, value]) => <div key={label}><strong>{percent(value)}</strong><span>{label}</span></div>)}</div><dl className="metadata"><dt>Eligible samples</dt><dd>{metrics.test_samples} · {metrics.class_counts.legitimate} legitimate / {metrics.class_counts.phishing} phishing</dd><dt>Excluded</dt><dd>{Object.entries(report.excluded).map(([key, value]) => `${key.replaceAll('_', ' ')}: ${value}`).join(' · ')}</dd><dt>False positives / negatives</dt><dd>{metrics.confusion_matrix[0][1]} / {metrics.confusion_matrix[1][0]} at threshold 0.5</dd><dt>False-positive rate</dt><dd>{percent(metrics.false_positive_rate)}</dd><dt>Collection dates</dt><dd>{report.collection_date_range?.join(' to ')}</dd><dt>Sampling</dt><dd>{report.sampling}</dd></dl><div className="notice warning">{report.limitations}</div><p className="small">The original model performed poorly on a different diagnostic slice, prompting modern training data. These final figures use a reserved slice and are lower than same-source hold-out scores. Email still lacks independent modern evaluation.</p></section>;
}

function ModelCard({ title, model }) {
  const m = model.metrics;
  return <section className="card model-card"><div className="eyebrow">{title}</div><h2>{model.name}</h2><p>{model.dataset}</p><div className="model-stats">{[['Accuracy', m.accuracy], ['Precision', m.precision], ['Recall', m.recall], ['F1 score', m.f1]].map(([label, value]) => <div key={label}><strong>{percent(value)}</strong><span>{label}</span></div>)}</div><dl className="metadata"><dt>Samples</dt><dd>{model.samples.toLocaleString()} total / {model.train_samples.toLocaleString()} training / {m.test_samples.toLocaleString()} test</dd><dt>Features</dt><dd>{model.features.toLocaleString()}</dd><dt>Split strategy</dt><dd>{model.split}</dd><dt>False-positive rate</dt><dd>{percent(m.false_positive_rate)} at model threshold 0.5</dd><dt>ROC AUC</dt><dd>{m.roc_auc}</dd></dl><h3>Held-out confusion matrix</h3><div className="confusion-matrix"><span /><span>Predicted legitimate</span><span>Predicted phishing</span><span>Actual legitimate</span><strong>{m.confusion_matrix[0][0]}<small>True negatives</small></strong><strong className="matrix-error">{m.confusion_matrix[0][1]}<small>False positives</small></strong><span>Actual phishing</span><strong className="matrix-error">{m.confusion_matrix[1][0]}<small>False negatives</small></strong><strong>{m.confusion_matrix[1][1]}<small>True positives</small></strong></div><div className="notice warning">{model.limitations}</div></section>;
}

export default function ModelLab() {
  const resource = useResource('/models');
  const evaluation = resource.data?.evaluation;
  return <><div className="page-heading"><div><div className="eyebrow">EVIDENCE, NOT A CLAIM</div><h1>Inside the models<span className="heading-dot">.</span></h1><p>Training provenance, held-out performance and honest limitations.</p></div></div>{resource.error && <div className="notice error">{resource.error}</div>}{resource.loading ? <p>Loading evaluation…</p> : !evaluation ? <div className="card">Models are not trained yet. Run <code>python -m backend.train --download</code> and restart the API.</div> : <><div className="notice">Trained {formatDate(evaluation.trained_at)} · seed {evaluation.seed} · scikit-learn {evaluation.sklearn_version} · positive class: phishing. Metrics describe each individual model at 0.5; they do not evaluate the combined email/link policy or your custom alert threshold.</div><div className="model-grid"><ModelCard title="URL CLASSIFICATION" model={evaluation.url} /><ModelCard title="EMAIL CLASSIFICATION" model={evaluation.email} /></div><CalibrationCard title="URL calibration" model={evaluation.url} /><CalibrationCard title="Email calibration" model={evaluation.email} /><BenchmarkCard report={evaluation.external_evaluation} /><ExternalEvaluation /><section className="card"><h2>Algorithm comparison</h2><p>URL candidates were compared on validation F1 before the final hold-out was evaluated.</p><div className="table-responsive"><table><thead><tr><th>Candidate</th><th>Validation accuracy</th><th>Validation precision</th><th>Validation recall</th><th>Validation F1</th></tr></thead><tbody>{Object.entries(evaluation.url.validation_comparison).map(([name, metrics]) => <tr key={name}><td>{name}{name === evaluation.url.name && <span className="selected-tag">SELECTED</span>}</td>{['accuracy', 'precision', 'recall', 'f1'].map(key => <td key={key}>{percent(metrics[key])}</td>)}</tr>)}</tbody></table></div></section><section className="card"><h2>Global URL feature importance</h2><p>Feature importance summarizes the trained model; it does not explain a particular URL.</p><div className="importance-list">{evaluation.url.top_features.map(item => <div key={item.name}><span>{item.name.replaceAll('_', ' ')}</span><div className="importance-track"><i style={{ width: `${Math.min(100, item.importance * 100)}%` }} /></div><code>{item.importance.toFixed(3)}</code></div>)}</div></section><section className="card"><h2>Dataset provenance</h2><p>UCI and a separate PhreshPhish publisher training slice supply URL labels. Supplied website features and HTML are discarded; lexical features are recomputed locally.</p>{evaluation.sources.map(source => <div className="source-row" key={source.file}><a href={source.url} target="_blank" rel="noreferrer">{source.file} ↗</a><code>SHA-256: {source.sha256}</code></div>)}<p className="small">URL samples are separated by registered domain, including private hosting suffixes. Email vocabulary is fitted on training data only. See DATASETS.md for attribution and limitations.</p></section></>}</>;
}
