// Optional browser smoke test: npm install --no-save playwright, or set PLAYWRIGHT_MODULE.
// Uses an isolated browser context and creates a disposable local test account.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const output = path.resolve('artifacts/browser');
  fs.mkdirSync(output, { recursive: true });
  const username = `browser_test_${Date.now()}`;
  const password = 'DisposableTest!123';
  const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'msedge' });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, acceptDownloads: true });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const results = [];
  try {
    await page.goto(process.env.APP_URL || 'http://127.0.0.1:8000/');
    await page.getByRole('heading', { name: 'Welcome back' }).waitFor();
    await page.screenshot({ path: path.join(output, 'login-desktop.png'), fullPage: true });
    await page.getByRole('button', { name: 'New here? Create an account' }).click();
    await page.getByLabel('Username', { exact: true }).fill(username);
    await page.getByLabel('Password', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Create account →', exact: true }).click();
    await page.getByRole('heading', { name: 'Detection center.' }).waitFor();
    await page.getByText('ML engine ready').waitFor();
    results.push('Registration through UI and server session');
    await page.getByRole('button', { name: 'Ordinary URL', exact: true }).click();
    const scanPromise = page.waitForResponse(response => response.url().endsWith('/api/scan/url') && response.request().method() === 'POST');
    await page.getByRole('button', { name: 'Analyze URL →', exact: true }).click();
    const ordinary = await (await scanPromise).json();
    assert.equal(ordinary.risk_level, 'Low');
    await page.getByRole('heading', { name: 'URL security report' }).waitFor();
    await page.screenshot({ path: path.join(output, 'dashboard-desktop.png'), fullPage: true });
    results.push('URL scan UI → API → stored report → rendered low risk result');
    await page.getByRole('button', { name: 'Block host', exact: true }).click();
    await page.getByText('www.wikipedia.org added to your in-app blocklist.').waitFor();
    const denied = await context.request.post('http://127.0.0.1:8000/api/link-access', { headers: { 'X-PhishGuard': '1' }, data: { url: ordinary.url } });
    assert.equal((await denied.json()).allowed, false);
    results.push('New blocklist entry denies a previously low risk destination');
    const pdfPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download PDF' }).click();
    const pdf = await pdfPromise;
    await pdf.saveAs(path.join(output, 'url-report.pdf'));
    assert.equal(fs.readFileSync(path.join(output, 'url-report.pdf')).subarray(0, 5).toString(), '%PDF-');
    const jsonPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export JSON', exact: true }).click();
    await (await jsonPromise).saveAs(path.join(output, 'url-report.json'));
    assert.equal(JSON.parse(fs.readFileSync(path.join(output, 'url-report.json'))).id, ordinary.id);
    results.push('PDF and JSON exports downloaded successfully');
    await page.getByRole('tab', { name: 'Email scanner' }).click();
    await page.getByRole('button', { name: 'Suspicious sample', exact: true }).click();
    const emailPromise = page.waitForResponse(response => response.url().endsWith('/api/scan/email') && response.request().method() === 'POST');
    await page.getByRole('button', { name: 'Analyze email →', exact: true }).click();
    const email = await (await emailPromise).json();
    assert.equal(email.risk_level, 'High');
    assert.equal(email.features.reply_mismatch, 1);
    assert.equal(email.features.link_label_mismatch, 1);
    await page.getByRole('heading', { name: 'Email security report' }).waitFor();
    await page.getByRole('alert').filter({ hasText: 'High risk detected' }).waitFor();
    await page.screenshot({ path: path.join(output, 'email-desktop.png'), fullPage: true });
    const emailPDFPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download PDF' }).click();
    await (await emailPDFPromise).saveAs(path.join(output, 'email-report.pdf'));
    results.push('Email analysis and alert show learned risk, header mismatch and embedded links');
    await page.getByRole('button', { name: 'Scan reports' }).click();
    assert.equal(await page.getByRole('button', { name: 'View →' }).count(), 2);
    await page.getByRole('button', { name: 'View →' }).first().click();
    await page.getByRole('heading', { name: 'Email security report' }).waitFor();
    results.push('Saved history reloads the detailed report');
    await page.getByRole('button', { name: 'Model lab' }).click();
    await page.getByRole('heading', { name: 'Random Forest', exact: true }).waitFor();
    const modelResponse = await context.request.get('http://127.0.0.1:8000/api/models');
    const modelData = await modelResponse.json();
    await page.getByText(`${(modelData.evaluation.url.metrics.accuracy * 100).toFixed(2)}%`, { exact: true }).first().waitFor();
    await page.screenshot({ path: path.join(output, 'models-desktop.png'), fullPage: true });
    results.push('Model Lab displays actual evaluation and bias limitations');
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    await page.getByLabel('High risk threshold').fill('60');
    await page.getByLabel('Automatically block high risk URL hosts').check();
    await page.getByRole('button', { name: 'Save preferences', exact: true }).click();
    await page.getByRole('status').filter({ hasText: 'Protection settings saved' }).waitFor();
    await page.getByRole('button', { name: 'Detection center', exact: true }).click();
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    assert.equal(await page.getByLabel('High risk threshold').inputValue(), '60');
    assert.equal(await page.getByLabel('Automatically block high risk URL hosts').isChecked(), true);
    results.push('Settings persist across navigation');
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Menu', exact: true }).click();
    await page.getByRole('button', { name: 'Detection center', exact: true }).click();
    await page.getByRole('heading', { name: 'Detection center.' }).waitFor();
    await page.waitForFunction(() => document.querySelector('.sidebar').getBoundingClientRect().right <= 0);
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile viewport has horizontal overflow');
    await page.screenshot({ path: path.join(output, 'dashboard-mobile.png'), fullPage: true });
    results.push('Mobile navigation and layout at 390 px without horizontal overflow');
    assert.deepEqual(errors, []);
    results.push('No uncaught browser errors');
    fs.writeFileSync(path.join(output, 'results.json'), JSON.stringify({ username, passed: results, errors }, null, 2));
    console.log(JSON.stringify({ username, passed: results, errors }, null, 2));
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
